Repository andy-keene/sps-project-2022, pull requests merged in 2022-07, with the labels that each got.

#1 Add Gson and Datastore dependencies
  project/pom.xml
Labels: enhancement

#2 Create `Resource` object
  project/pom.xml
  project/src/main/java/com/google/sps/servlets/Resource.java
  project/src/main/java/com/google/sps/servlets/ResourceHandlerServlet.java
  project/src/main/java/com/google/sps/servlets/ResourceListServlet.java
  project/src/main/webapp/addEvent.html
  project/src/main/webapp/index.html
Labels: enhancement

#12 Retrieve datastore objects for front-end
  project/src/main/java/com/google/sps/servlets/Resource.java
  project/src/main/java/com/google/sps/servlets/ResourceHandlerServlet.java
  project/src/main/java/com/google/sps/servlets/ResourceListServlet.java
  project/src/main/webapp/add-event.html
Labels: Work In Progress, Backend

#10 Connect start page with other pages and create sample js file for datastore display
  project/src/main/webapp/event-page.html
  project/src/main/webapp/script.js
Labels: Frontend

#13 Finish datastore display and fix small bug in add-event page
  project/src/main/java/com/google/sps/servlets/ResourceHandlerServlet.java
  project/src/main/java/com/google/sps/servlets/ResourceListServlet.java
  project/src/main/webapp/add-event.html
  project/src/main/webapp/index.html
  project/src/main/webapp/script.js
  project/src/main/webapp/view-events.css
  project/src/main/webapp/view-events.html
Labels: Frontend

#14 Add timestamp to Resource object and Datastore
  project/src/main/java/com/google/sps/servlets/Resource.java
  project/src/main/java/com/google/sps/servlets/ResourceHandlerServlet.java
  project/src/main/java/com/google/sps/servlets/ResourceListServlet.java
Labels: Backend
